LFG/Models/Group.cs
using LFG.Enums;
using LFG.Validation;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LFG.Models
{
  public class Group
  {
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    [Required]
    [UniqueGroupName]
    [Length(3, 30)]
    [RegularExpression(@"^[A-Za-z]+[\w -]+")]
    public string Name { get; set; }

    [Required]
    public int Owner { get; set; }

    [MaxLength(250)]
    public string? Description { get; set; }

    [Required]
    public bool Public { get; set; }

    [Required]
    public GroupStatus Status { get; set; }

    public int? AvatarId { get; set; }

    [Required]
    [DataType(DataType.Date)]
    public DateTime Created { get; set; }
  }
}

LFG/Pages/Group/GameGroups.cshtml.cs
using LFG.Data;
using LFG.Hubs;
using LFG.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;

namespace LFG.Pages.Group
{
  [Authorize(Policy = "Registered")]
  [BindProperties(SupportsGet = true)]
  public class GameGroupsModel : PageModel
  {
    private readonly LFGContext _context;
    private readonly IHubContext<GroupSearchHub> _groupSearchHubContext;

    public GameGroupsModel(LFGContext context, IHubContext<GroupSearchHub>? groupSearchHubContext)
    {
      _context = context;
      if (groupSearchHubContext != null) _groupSearchHubContext = groupSearchHubContext;
    }

    public Game Game { get; set; }
    public Company GameDeveloper { get; set; }
    public Company GamePublisher { get; set; }
    public List<Platform> GamePlatforms { get; set; }
    public List<string> GamePlatformNames { get; set; }
    public List<Models.Group> GameGroups { get; set; }
    public Models.Group Group { get; set; }
    public string? SelectedGroup { get; set; }
    public string? CreateGroupErrorMessage { get; set; } = null;

    public async Task OnGetAsync()
    {
      Game = await _context.Games.FirstOrDefaultAsync(g => g.Name == RouteData.Values["game"]);
      GameDeveloper = await _context.GamesDevelopers
        .Where(d => d.GameId == Game.Id)
        .Include(d => d.Company)
        .Select(d => new Company
        {
          Name = d.Company.Name,
          LogoId = d.Company.LogoId
        })
        .SingleAsync();
      GamePublisher = await _context.GamesPublishers
        .Where(p => p.GameId == Game.Id)
        .Include(p => p.Company)
        .Select(p => new Company
        {
          Name = p.Company.Name,
          LogoId = p.Company.LogoId
        })
        .SingleAsync();
      GamePlatforms = await _context.GamesPlatforms
        .Where(p => p.GameId == Game.Id)
        .Include(p => p.Platform)
        .Select(p => new Platform
        {
          Name = p.Platform.Name
        })
        .ToListAsync();
      GamePlatformNames = GamePlatforms.Select(p => p.Name).ToList();

      GameGroups = await _context.GroupsGames
        .Where(g => g.GameId == Game.Id)
        .Include(g => g.Group)
        .Select(g => new Models.Group
        {
          Name = g.Group.Name,
          Description = g.Group.Description,
          Public = g.Group.Public,
          AvatarId = g.Group.AvatarId
        })
        .ToListAsync();
    }

    public async Task OnPostGroupSearch()
    {
      Game = await _context.Games.FirstOrDefaultAsync(g => g.Name == RouteData.Values["game"]);
      GameGroups = await _context.GroupsGames
        .Where(g => g.GameId == Game.Id)
        .Include(g => g.Group)
        .Select(g => new Models.Group
        {
          Name = g.Group.Name,
          Description = g.Group.Description,
          Public = g.Group.Public,
          AvatarId = g.Group.AvatarId
        })
        .ToListAsync();

      await _groupSearchHubContext.Clients.All.SendAsync("groupSearch", GameGroups, SelectedGroup);
    }

    public async Task<IActionResult> OnPostCreateGroup()
    {
      ModelState.MaxAllowedErrors = 4;
      if (ModelState.HasReachedMaxErrors)
      {
        CreateGroupErrorMessage = "Fields are invalid. Please try again.";
        await OnGetAsync();
        return Page();
      }

      Group.Owner = await _context.Users.Where(u => u.Username == User.Identity.Name).Select(u => u.Id).SingleAsync();
      Group.Created = DateTime.Now;

      await _context.Groups.AddAsync(Group);
      await _context.SaveChangesAsync();

      var newGroup = await _context.Groups.FirstOrDefaultAsync(g => g.Name == Group.Name);
      Game = await _context.Games.FirstOrDefaultAsync(g => g.Name == RouteData.Values["game"]);
      var newGroupGame = new GroupGame
      {
        GroupId = newGroup.Id,
        GameId = Game.Id
      };
      var newUserGroup = new UserGroup
      {
        UserId = Group.Owner,
        GroupId = newGroup.Id,
        Rank = 1,
        Role = Enums.GroupRole.Owner
      };

      await _context.GroupsGames.AddAsync(newGroupGame);
      await _context.UsersGroups.AddAsync(newUserGroup);
      await _context.SaveChangesAsync();

      return RedirectToPage("/Group/Group", new { groupname = newGroup.Name });
    }
  }
}

LFG/Pages/Group/Group.cshtml.cs
using LFG.Data;
using LFG.Enums;
using LFG.Hubs;
using LFG.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using Thread = LFG.Models.Thread;

namespace LFG.Pages.Group
{
  [Authorize(Policy = "Registered")]
  [BindProperties(SupportsGet = true)]
  public class GroupModel : PageModel
  {
    private readonly LFGContext _context;
    private readonly IHubContext<ThreadVoteHub> _threadVoteHubContext;
    private readonly IHubContext<CommentVoteHub> _commentVoteHubContext;
    private readonly IHubContext<GroupPageHub> _groupPageHubContext;

    public GroupModel(LFGContext context, IHubContext<ThreadVoteHub> threadVoteHubContext, IHubContext<CommentVoteHub> commentVoteHubContext, IHubContext<GroupPageHub>? groupPageHubContext)
    {
      _context = context;
      _threadVoteHubContext = threadVoteHubContext;
      _commentVoteHubContext = commentVoteHubContext;
      if (groupPageHubContext != null) _groupPageHubContext = groupPageHubContext;
    }

    public User User { get; set; }
    public UserGroup? UserGroup { get; set; }
    public GroupRole UserRole { get; set; }
    public Models.Group Group { get; set; }
    public User Owner { get; set; }
    public int GroupMemberCount { get; set; }
    public List<GroupLink> GroupLinks { get; set; }
    public Website SelectedSite { get; set; }

    [DataType(DataType.Url)]
    [Display(Name = "Link")]
    public string? InputLink { get; set; }

    [RegularExpression(@"[\w \-%]+", ErrorMessage = "Invalid URL")]
    [Display(Name = "Link")]
    public string? InputSubdirectory { get; set; }
    public string LinkToRemove { get; set; }
    public List<Game> GroupGames { get; set; }
    public List<string> GroupGameNames { get; set; }
    public List<string> AllGamesList { get; set; }
    public string SelectedGame { get; set; }
    public string GameToRemove { get; set; }
    public List<Thread> GroupThreads { get; set; }
    public List<Comment> ThreadComments { get; set; }
    public Thread Thread { get; set; }
    public Comment Comment { get; set; }

    public string? LinkExists { get; set; }
    public string? GameExists { get; set; }

    public async Task OnGetAsync()
    {
      Group = await _context.Groups.FirstOrDefaultAsync(g => g.Name == RouteData.Values["groupname"]);
      Owner = await _context.Users.FirstOrDefaultAsync(u => u.Id == Group.Owner);
      User = await _context.Users.FirstOrDefaultAsync(u => u.Username == HttpContext.User.Identity.Name);
      UserGroup = await _context.UsersGroups.FirstOrDefaultAsync(u => u.UserId == User.Id && u.GroupId == Group.Id);

      if (UserGroup != null)
      {
        UserRole = UserGroup.Role;
      }

      GroupMemberCount = _context.UsersGroups.Where(g => g.GroupId == Group.Id).Count();
      GroupLinks = await _context.GroupsLinks.Where(l => l.GroupId == Group.Id).ToListAsync();
      GroupGames = await _context.GroupsGames
        .Where(g => g.GroupId == Group.Id)
        .Include(g => g.Game)
        .Select(g => new Game
        {
          Name = g.Game.Name,
          CoverId = g.Game.CoverId
        })
        .ToListAsync();

      GroupGameNames = GroupGames.Select(g => g.Name).ToList();

      AllGamesList = await _context.Games.Select(g => g.Name).ToListAsync();

      GroupThreads = await _context.Threads.Where(t => t.GroupId == Group.Id).OrderByDescending(t => t.Pinned == true).ThenByDescending(t => t.Created).ThenBy(t => t.Id).ToListAsync();
    }

    public async Task OnPostUpdateGroupInfo(int groupId)
    {
      //Get Group
      Group = await _context.Groups.FindAsync(groupId);

      //Set Values From Form
      Group.Name = Request.Form["Group.Name"].ToString();
      Group.Description = Request.Form["Group.Description"].ToString();
      Group.Public = Request.Form["Group.Public"].Contains("true");
      Group.Status = GroupStatus.Parse<GroupStatus>(Request.Form["Group.Status"].ToString());

      //Update Group
      _context.Groups.Attach(Group).State = EntityState.Modified;
      await _context.SaveChangesAsync();

      //Call SignalR Method To Refresh Group Info
      await _groupPageHubContext.Clients.All.SendAsync("updateGroupInfo", groupId);
    }

    public async Task OnPostUpdateLinkForm()
    {
      Group = await _context.Groups.FirstOrDefaultAsync(g => g.Name == RouteData.Values["groupname"]);

      await _groupPageHubContext.Clients.All.SendAsync("updateLinkForm", Group.Id, SelectedSite);
    }

    public async Task OnPostAddLink()
    {
      ModelState.MaxAllowedErrors = 13;
      if (ModelState.HasReachedMaxErrors)
      {
        return;
      }

      Group = await _context.Groups.FirstOrDefaultAsync(g => g.Name == RouteData.Values["groupname"]);

      GroupLink linkToAdd;
      if (SelectedSite == Website.Other)
      {
        linkToAdd = new GroupLink
        {
          GroupId = Group.Id,
          SiteName = SelectedSite,
          Link = InputLink
        };
      }
      else
      {
        string baseUri = "";
        switch (SelectedSite)
        {
          case Website.Discord:
            baseUri = "https://discord.gg/";
            break;
          case Website.Facebook:
            baseUri = "https://facebook.com/groups/";
            break;
          case Website.Twitter:
            baseUri = "https://x.com/";
            break;
          case Website.Instagram:
            baseUri = "https://instagram.com/";
            break;
          case Website.Reddit:
            baseUri = "https://reddit.com/r/";
            break;
          case Website.Steam:
            baseUri = "https://steamcommunity.com/groups/";
            break;
        }

        linkToAdd = new GroupLink
        {
          GroupId = Group.Id,
          SiteName = SelectedSite,
          Link = baseUri + InputSubdirectory
        };
      }

      if (!_context.GroupsLinks.Contains(linkToAdd))
      {
        await _context.GroupsLinks.AddAsync(linkToAdd);
        await _context.SaveChangesAsync();
      }
      else
      {
        LinkExists = "Link already added";
      }

      await _groupPageHubContext.Clients.All.SendAsync("updateGroupInfo", Group.Id);
      await _groupPageHubContext.Clients.All.SendAsync("updateEditGroupInfo", Group.Id);
    }

    public async Task OnPostRemoveLink()
    {
      ModelState.MaxAllowedErrors = 12;
      if (ModelState.HasReachedMaxErrors)
      {
        return;
      }

      Group = await _context.Groups.FirstOrDefaultAsync(g => g.Name == RouteData.Values["groupname"]);

      var linkToRemoveLink = _context.GroupsLinks.Where(l => l.SiteName == Enum.Parse<Website>(LinkToRemove) && l.GroupId == Group.Id).Select(l => l.Link).Single();

      var linkToRemove = new GroupLink
      {
        GroupId = Group.Id,
        SiteName = Enum.Parse<Website>(LinkToRemove),
        Link = linkToRemoveLink
      };

      if (_context.GroupsLinks.Contains(linkToRemove))
      {
        _context.GroupsLinks.Remove(linkToRemove);
        await _context.SaveChangesAsync();
      }
      else
      {
        LinkExists = "Link has not been added";
      }

      await _groupPageHubContext.Clients.All.SendAsync("updateGroupInfo", Group.Id);
      await _groupPageHubContext.Clients.All.SendAsync("updateEditGroupInfo", Group.Id);
    }

    public async Task OnPostAddGame()
    {
      ModelState.MaxAllowedErrors = 12;
      if (ModelState.HasReachedMaxErrors)
      {
        return;
      }

      Group = await _context.Groups.FirstOrDefaultAsync(g => g.Name == RouteData.Values["groupname"]);

      var gameId = await _context.Games
        .Where(g => g.Name == SelectedGame)
        .Select(g => g.Id)
        .SingleAsync();

      var gameToAdd = new GroupGame
      {
        GroupId = Group.Id,
        GameId = gameId
      };

      if (!_context.GroupsGames.Contains(gameToAdd))
      {
        await _context.GroupsGames.AddAsync(gameToAdd);
        await _context.SaveChangesAsync();
      }
      else
      {
        GameExists = "Game already added";
      }

      await _groupPageHubContext.Clients.All.SendAsync("updateGroupGames", Group.Id);
      await _groupPageHubContext.Clients.All.SendAsync("updateEditGroupInfo", Group.Id);
    }

    public async Task OnPostRemoveGame()
    {
      ModelState.MaxAllowedErrors = 12;
      if (ModelState.HasReachedMaxErrors)
      {
        return;
      }

      Group = await _context.Groups.FirstOrDefaultAsync(g => g.Name == RouteData.Values["groupname"]);

      var gameId = await _context.Games
        .Where(g => g.Name == GameToRemove)
        .Select(g => g.Id)
        .SingleAsync();

      var gameToRemove = new GroupGame
      {
        GroupId = Group.Id,
        GameId = gameId
      };

      if (_context.GroupsGames.Contains(gameToRemove))
      {
        _context.GroupsGames.Remove(gameToRemove);
        await _context.SaveChangesAsync();
      }
      else
      {
        GameExists = "Game has not been added";
      }

      await _groupPageHubContext.Clients.All.SendAsync("updateGroupGames", Group.Id);
      await _groupPageHubContext.Clients.All.SendAsync("updateEditGroupInfo", Group.Id);
    }

    public async Task<IActionResult> OnPostJoin()
    {
      //Get Group and User Info
      Group = await _context.Groups.FirstOrDefaultAsync(g => g.Name == RouteData.Values["groupname"]);
      User = await _context.Users.FirstOrDefaultAsync(u => u.Username == HttpContext.User.Identity.Name);
      UserGroup = await _context.UsersGroups.FirstOrDefaultAsync(u => u.UserId == User.Id && u.GroupId == Group.Id);

      //Check If User Is Already A Member
      if (UserGroup != null) return Page();

      //Add User To Group
      await _context.UsersGroups.AddAsync(new UserGroup
      {
        UserId = User.Id,
        GroupId = Group.Id,
        Rank = 1,
        Role = GroupRole.Member
      });

LFG/Pages/Group/GroupMembers.cshtml.cs
using LFG.Data;
using LFG.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace LFG.Pages.Group
{
  [Authorize(Policy = "Registered")]
  public class GroupMembersModel : PageModel
  {
    public readonly LFGContext _context;

    public GroupMembersModel(LFGContext context)
    {
      _context = context;
    }

    public Models.Group Group { get; set; }
    public List<UserGroup> GroupMembers { get; set; }
    public SortedList<int, string> Usernames { get; set; } = [];

    public async Task OnGetAsync()
    {
      Group = await _context.Groups.FirstOrDefaultAsync(g => g.Name == RouteData.Values["groupname"]);
      GroupMembers = await _context.UsersGroups.Where(g => g.GroupId == Group.Id).ToListAsync();
      GroupMembers.ForEach(m =>
      {
        var username = _context.Users.Where(u => u.Id == m.UserId).Select(u => u.Username).Single();
        Usernames.Add(m.UserId, username);
      });
    }
  }
}

LFG/Pages/Group/Group.cshtml
@page "/Group/{groupname}"

@using System.Collections
@using LFG.Models
@model GroupModel
@{
  ViewData["Title"] = Model.Group.Name;
}

<div class="group-heading">
  <h1>@Model.Group.Name</h1>
  <div class="small-button-block">
    @if (Model.Owner.Username == User.Identity.Name)
    {
      <button class="edit-button small-button" onclick="toggleEditGroupInfo()">Edit</button>
    }
    @if (Model.UserGroup == null && Model.Group.Public)
    {
      <form id="join-form" method="post" asp-page-handler="Join"></form>
      <button class="join-button small-button" form="join-form">
        Join
      </button>
    }
    <div class="buttons">
      <a class="small-button" asp-page="/Group/GroupMembers" asp-route-groupname="@Model.Group.Name">Members</a>
    </div>
  </div>
</div>
<div id="group-card" style="display:grid">
  <partial id="group-card-partial" name="Shared/_GroupCardPartial" />
</div>
<div id="edit-group-card" style="display:none">
  <partial id="group-card-partial" name="Shared/_EditGroupCardPartial" />
</div>
<button id="toggle-games" onclick="toggleGames()">Show Games</button>
<div id="games-list">
  <partial name="_GamesListPartial" />
</div>
<div class="start-a-thread-group">
  <button id="start-a-thread-button" onclick="toggleStartAThread()">Start A Thread</button>
  <div id="start-a-thread" style="height: 0rem;">
    <div class="start-a-thread-block">
      <form id="start-a-thread-form">
        @Html.AntiForgeryToken()
        <div class="form-item">
          <label asp-for="Thread.Title"></label>
          <input type="text" asp-for="Thread.Title" required/>
        </div>
        <div class="form-item">
          <label asp-for="Thread.Body"></label>
          <textarea class="thread-form-body" asp-for="Thread.Body" maxlength="40000" required></textarea>
        </div>
        <div class="form-item">
          <label asp-for="Thread.Pinned"></label>
          <input class="pinned-checkbox" type="checkbox" asp-for="Thread.Pinned"/>
        </div>
        <button type="submit" onclick="toggleStartAThread()">Create</button>
      </form>
    </div>
  </div>
</div>
@if (Model.UserGroup != null)
{
  <div id="threads" class="threads">
    <partial name="Shared/_GroupThreadsPartial" model="Model"/>
  </div>
}

@section Scripts
{
  <partial name="_ValidationScriptsPartial" />
  <script src="~/lib/jquery/dist/jquery.js"></script>
  <script src="~/lib/microsoft/signalr/dist/browser/signalr.js"></script>
  <script src="~/js/threadrating.js"></script>
  <script src="~/js/commentrating.js"></script>
  <script src="~/js/grouppage.js"></script>
  <script type="text/javascript">

    $(document).on("change", "#site-select", function (e) {
      e.preventDefault();
      var form = $(this);
      var token = $('input[name="__RequestVerificationToken"]').val();

      $.ajax({
        url: `?handler=UpdateLinkForm`,
        type: 'POST',
        headers: {
          RequestVerificationToken: token
        },
        data: form.serialize()
      });
    });

    @* Toggle Edit Group Info *@
    function toggleEditGroupInfo() {
      const groupCard = document.getElementById("group-card");
      const editGroupCard = document.getElementById("edit-group-card");

      if (groupCard.style.display === "grid") {
        groupCard.style.display = "none";
        editGroupCard.style.display = "grid";
      } else {
          groupCard.style.display = "grid";
          editGroupCard.style.display = "none";
      }
    }

    @* Edit Group Info *@
    $(document).on("submit", "#group-info-form", function (e) {
      e.preventDefault();
      var form = $(this);
      var groupId = form.find("#groupId").val();

      $.ajax({
        url: `?groupId=${groupId}&handler=UpdateGroupInfo`,
        type: 'POST',
        data: form.serialize()
      });

      toggleEditGroupInfo();
    });

     @* Add Link *@
    $(document).on("submit", "#link-form", function (e) {
      e.preventDefault();
      var form = $(this);

      $.ajax({
        url: `?handler=AddLink`,
        type: 'POST',
        data: form.serialize()
      });
    });

    @* Remove Link *@
    $(document).on("submit", "#remove-link-form", function (e) {
      e.preventDefault();
      var form = $(this);

      $.ajax({
        url: `?handler=RemoveLink`,
        type: 'POST',
        data: form.serialize()
      });
    });

    @* Add Game *@
    $(document).on("submit", "#game-form", function (e) {
      e.preventDefault();
      var form = $(this);

      $.ajax({
        url: `?handler=AddGame`,
        type: 'POST',
        data: form.serialize()
      });
    });

    @* Remove Game *@
    $(document).on("submit", "#remove-game-form", function (e) {
      e.preventDefault();
      var form = $(this);

      $.ajax({
        url: `?handler=RemoveGame`,
        type: 'POST',
        data: form.serialize()
      });
    });

    @* Toggle Group Games List *@
    function toggleGames() {
      const gamesList = document.getElementById("games-list");
      const toggleGames = document.getElementById("toggle-games");

      if (gamesList.style.display === "block") {
        gamesList.style.display = "none";
        toggleGames.innerHTML = "Show Games";
      } else {
        gamesList.style.display = "block";
        toggleGames.innerHTML = "Hide Games";
      }
    }

    @* Toggle Create Thread Form *@
    function toggleStartAThread() {
      const startAThread = document.getElementById("start-a-thread");
      const startAThreadForm = document.getElementById("start-a-thread-form");

      if (startAThread.style.height === "0rem") {
        startAThread.style.height = "27rem";
        startAThreadForm.style.opacity = "1";
      } else {
        startAThread.style.height = "0rem";
        startAThreadForm.style.opacity = "0";
      }
    }

    @* Create Thread *@
    $(document).on("submit", "#start-a-thread-form", function(e) {
      e.preventDefault();
      var form = $(this);
        
      $.ajax({
        url: `?handler=CreateThread`,
        type: 'POST',
        data: form.serialize()
      });
    });

    @* Edit Thread *@
    $(document).on("submit", "#edit-thread-form", function (e) {
      e.preventDefault();
      var form = $(this);
      var threadId = form.find("#threadId").val();

      $.ajax({
        url: `?threadId=${threadId}&handler=UpdateGroupThread`,
        type: 'POST',
        data: form.serialize()
      });
    });

    @* Delete Thread *@
    $(document).on("submit", "#delete-thread-form", function (e) {
      e.preventDefault();
      var form = $(this);
      var threadId = form.find("#threadId").val();

      $.ajax({
        url: `?threadId=${threadId}&handler=DeleteThread`,
        type: 'POST',
        data: form.serialize()
      });
    });

    @* Create Comment *@
    $(document).on("submit", "#comment-form", function (e) {
      e.preventDefault();
      var form = $(this);
      var threadId = form.find("#threadId").val();

      $.ajax({
        url: `?threadId=${threadId}&handler=CreateComment`,
        type: 'POST',
        data: form.serialize()
      });
    });

    @* Edit Comment *@
    $(document).on("submit", "#edit-comment-form", function (e) {
      e.preventDefault();
      var form = $(this);
      console.log(form);
      var threadId = form.find("#threadId").val();
      var commentId = form.find("#commentId").val();

      $.ajax({
        url: `?threadId=${threadId}&commentId=${commentId}&handler=UpdateComment`,
        type: 'POST',
        data: form.serialize()
      });
    });

    @* Delete Comment *@
    $(document).on("submit", "#comment-delete-form", function (e) {
      e.preventDefault();
      var form = $(this);
      var commentId = form.find("#commentId").val();

      $.ajax({
        url: `?commentId=${commentId}&handler=DeleteComment`,
        type: 'POST',
        data: form.serialize()
      });
    });

    @* Toggle Thread Comments List *@
    function showComments(threadId) {
      const threadComments = document.getElementById(`comments-${threadId}`);

      if (threadComments.style.display === "block") {
        threadComments.style.display = "none";
      } else {
        threadComments.style.display = "block";
      }
    }

    @* Upvote Thread *@
    function upvoteThread(threadId) {
      var token = $('input[name="__RequestVerificationToken"]').val();
      $.ajax({
        url: `?threadId=${threadId}&handler=UpvoteThread`,
        type: 'POST',
        data: {
          __RequestVerificationToken: token
        }
      });
    }

    @* Downvote Thread *@
    function downvoteThread(threadId) {
      var token = $('input[name="__RequestVerificationToken"]').val();
      $.ajax({
        url: `?threadId=${threadId}&handler=DownvoteThread`,
        type: 'POST',
        data: {
          __RequestVerificationToken: token
        }
      });
    }

    @* Upvote Comment *@
    function upvoteComment(commentId) {
      var token = $('input[name="__RequestVerificationToken"]').val();
      $.ajax({
        url: `?commentId=${commentId}&handler=UpvoteComment`,
        type: 'POST',
        data: {
          __RequestVerificationToken: token
        }
      });
    }

    @* Downvote Comment *@
    function downvoteComment(commentId) {
      var token = $('input[name="__RequestVerificationToken"]').val();
      $.ajax({
        url: `?commentId=${commentId}&handler=DownvoteComment`,
        type: 'POST',
        data: {
          __RequestVerificationToken: token
        }
      });
    }

    @* Toggle Edit Thread Form *@
    function threadEditMode(threadId) {
      const thread = document.getElementById(`thread-${threadId}`);
      const threadEdit = document.getElementById(`edit-thread-${threadId}`);

      if (thread.style.display === "flex") {
        thread.style.display = "none";
        threadEdit.style.display = "flex";
      } else {
        thread.style.display = "flex";
        threadEdit.style.display = "none";
      }
    }

    @* Toggle Edit Comment Form *@
    function commentEditMode(commentId) {
      const comment = document.getElementById(`comment-${commentId}`);
      const commentEdit = document.getElementById(`edit-comment-${commentId}`);

      if (comment.style.display === "block") {
        comment.style.display = "none";
        commentEdit.style.display = "block";
      } else {
        comment.style.display = "block";
        commentEdit.style.display = "none";
      }
    }

    @* Show Delete Thread Prompt *@
    function showConfirmDelete(threadId) {
      const confirmDelete = document.getElementById(`confirm-delete-${threadId}`);

      confirmDelete.style.display = "flex";
    }

    @* Hide Delete Thread Prompt *@
    function hideConfirmDelete(threadId) {
      const confirmDelete = document.getElementById(`confirm-delete-${threadId}`);

      confirmDelete.style.display = "none";
    }

    @* Show Delete Comment Prompt *@
    function showConfirmDeleteComment(commentId) {
      const confirmDelete = document.getElementById(`confirm-delete-comment-${commentId}`);

      confirmDelete.style.display = "flex";
    }

    @* Hide Delete Comment Prompt *@
    function hideConfirmDeleteComment(commentId) {
      const confirmDelete = document.getElementById(`confirm-delete-comment-${commentId}`);

      confirmDelete.style.display = "none";
    }
  </script>
}